enum SocialStatusEnum {
    NA = -1,
    Jester = 13,
    Peasant = 12,
    Stonecutter = 11,
    Shepherdess = 10,
    Cook = 9,
    Mason = 8,
    Seamstress = 7,
    Knight = 6,
    Abbess = 5,
    Baroness = 4,
    Earl = 3,
    Archbishop = 2,
    Dalmuti = 1,
}